# Generated by Django 5.2.15 on 2026-09-20 15:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('llm', 'LLM'), ('decision', 'Decision'), ('search', 'Search'), ('embedding', 'Embedding')], default='llm', max_length=16)),
                ('base_url', models.URLField(blank=True, default='', max_length=1024)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('enabled', models.BooleanField(default=True)),
                ('cloud_only', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'db_table': 'ai_providers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('context_window', models.PositiveIntegerField(blank=True, null=True)),
                ('max_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('disabled', 'Disabled')], default='pending', max_length=16)),
                ('source', models.CharField(choices=[('models.dev', 'models.dev'), ('litellm', 'LiteLLM'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='db.aiprovider')),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'db_table': 'ai_models',
                'ordering': ('provider', 'key'),
            },
        ),
        migrations.CreateModel(
            name='Markup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=8)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markups', to='db.aiprovider')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Markup',
                'verbose_name_plural': 'Markups',
                'db_table': 'ai_markups',
            },
        ),
        migrations.CreateModel(
            name='ModelAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('scope', models.CharField(choices=[('instance', 'Instance'), ('workspace', 'Workspace'), ('agent', 'Agent')], default='instance', max_length=16)),
                ('agent_id', models.UUIDField(blank=True, null=True)),
                ('feature', models.CharField(max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fallback_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_assignments', to='db.aimodel')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='db.aimodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_assignments', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Model Assignment',
                'verbose_name_plural': 'Model Assignments',
                'db_table': 'ai_model_assignments',
                'ordering': ('feature', 'scope'),
            },
        ),
        migrations.CreateModel(
            name='ModelPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(choices=[('models.dev', 'models.dev'), ('litellm', 'LiteLLM'), ('manual', 'Manual')], default='manual', max_length=16)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('input_per_mtok', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('cached_input_per_mtok', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('cache_write_per_mtok', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('output_per_mtok', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('reasoning_per_mtok', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('per_call', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='db.aimodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Model Price',
                'verbose_name_plural': 'Model Prices',
                'db_table': 'ai_model_prices',
                'ordering': ('model', '-effective_from'),
            },
        ),
        migrations.AddConstraint(
            model_name='aiprovider',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slug',), name='ai_provider_unique_slug_when_live'),
        ),
        migrations.AddConstraint(
            model_name='aimodel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('provider', 'key'), name='ai_model_unique_provider_key_when_live'),
        ),
        migrations.AddConstraint(
            model_name='markup',
            constraint=models.CheckConstraint(condition=models.Q(('multiplier__gt', 0)), name='ai_markup_multiplier_is_positive'),
        ),
        migrations.AddConstraint(
            model_name='markup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('provider__isnull', False)), fields=('provider',), name='ai_markup_unique_provider_when_live'),
        ),
        migrations.AddConstraint(
            model_name='markup',
            constraint=models.UniqueConstraint(models.Value(True), condition=models.Q(('deleted_at__isnull', True), ('provider__isnull', True)), name='ai_markup_one_instance_default'),
        ),
        migrations.AddConstraint(
            model_name='modelassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('agent_id__isnull', True), ('scope', 'instance'), ('workspace__isnull', True)), models.Q(('agent_id__isnull', True), ('scope', 'workspace'), ('workspace__isnull', False)), models.Q(('agent_id__isnull', False), ('scope', 'agent'), ('workspace__isnull', False)), _connector='OR'), name='ai_model_assignment_scope_matches_target'),
        ),
        migrations.AddConstraint(
            model_name='modelassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('scope', 'instance')), fields=('feature',), name='ai_model_assignment_unique_instance_feature'),
        ),
        migrations.AddConstraint(
            model_name='modelassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('scope', 'workspace')), fields=('workspace', 'feature'), name='ai_model_assignment_unique_workspace_feature'),
        ),
        migrations.AddConstraint(
            model_name='modelassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('scope', 'agent')), fields=('agent_id', 'feature'), name='ai_model_assignment_unique_agent_feature'),
        ),
        migrations.AddConstraint(
            model_name='modelprice',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('effective_to__isnull', True)), fields=('model',), name='ai_model_price_one_open_price_per_model'),
        ),
        migrations.AddConstraint(
            model_name='modelprice',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gt', models.F('effective_from')), _connector='OR'), name='ai_model_price_window_is_ordered'),
        ),
    ]
